name: record
description: Audio recorder from microphone to a given file path with multiple codecs, bit rate and sampling rate options.
version: 4.1.1
homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^0.3.0
  record_web: '>=0.3.0 < 2.0.0'
  record_macos: '>=0.1.0 < 2.0.0'

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
      ios:
        pluginClass: RecordPlugin
      web:
        default_package: record_web
      macos:
        default_package: record_macos
